# CMake generated Testfile for 
# Source directory: /root/AICAS/llama-cpp-python/vendor/llama.cpp/examples
# Build directory: /root/AICAS/llama-cpp-python/vendor/llama.cpp/build_not_show/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("baby-llama")
subdirs("batched")
subdirs("batched-bench")
subdirs("beam-search")
subdirs("benchmark")
subdirs("convert-llama2c-to-ggml")
subdirs("embedding")
subdirs("finetune")
subdirs("gritlm")
subdirs("gguf-split")
subdirs("infill")
subdirs("llama-bench")
subdirs("llava")
subdirs("main")
subdirs("tokenize")
subdirs("parallel")
subdirs("perplexity")
subdirs("quantize")
subdirs("quantize-stats")
subdirs("retrieval")
subdirs("save-load-state")
subdirs("simple")
subdirs("passkey")
subdirs("speculative")
subdirs("lookahead")
subdirs("lookup")
subdirs("gguf")
subdirs("train-text-from-scratch")
subdirs("imatrix")
subdirs("server")
subdirs("export-lora")
